### ISSUE TITLE
How to describe Enzyme cascades

### ISSUE THREAD

**Issue by StephanM87** [StephanM87/Strenda-biocatalysis#11]
### How can we describe a cascade in a combination of chemo and enzymatic reaction system

- Are we focussing on the description of each one vessel and how do we combine multiple vessels?

**Comment by KatrinRosenthal** [comment]
How to deal with sequential addition of compounds (substrates, enzymes) + different modes (some enzymes are added at the beginning of reaction, others as fed-batch or continuously)?

**Comment by StephanM87** [comment]
> 

Wouldn't this be an example for a combinatorial approach?

**Comment by PeterHalling** [comment]
I think we should distiniguish two very different experiments that can both be called "Cascade Reactions". In one case two or more catalysts (bio- or not) are present in the same reaction mixture. This just requires that the system allow the specification of more than one catalyst in the reaction mixture. We clearly need this, as it's rather common. Not just "cascade reactions", but e.g. cofactor recycling using a second enzyme, addition of catalase or chemical catalyst to destroy H2O2 produced in oxidase reactions, de-racemisation via 2-step reactions.
The second type of "cascade reaction" involves two or more vessels and reaction mixtures. Others will have more experience here, but I think usually these run in continuous mode, with the output of one being feed for the next, perhaps with further additions. So this requires another category in "Operation Mode", and the possibility to describe 2 different reaction mixtures, although some details of the second will be consequences (perhaps unknown) of what has happened in the the first.

**Comment by StephanM87** [comment]
In my perspective, this topic is very complex to discuss, I would like to put this issue on hold and further discuss it based on defined examples, in which we have to use exactly these cases, would this be fine?
