### ISSUE TITLE
Multi enzymatic complex biocatalyst

### ISSUE THREAD

**Issue by StephanM87** [StephanM87/Strenda-biocatalysis#13]
## How to deal with complexes of multiple enzyme subunits

I would like to create a subunit in the biocatalyst field for this case since it is a special case

- Also add a category for chemo enzymatic catalyst

**Comment by PeterHalling** [comment]
Can be solved by general approach of allowing description of more than one (bio)catalyst in the reaction mixture, I think. 
For multi-subunit biocatalysts, they might be handled in two different ways, depending on how experimenters apply them, and how they behave. 1) Prepare or obtain a single biocatalyst that is multi-subunit, which may or may not remain the same when added to the reaction mixture. 2) Prepare or obtain more than one "biocatalyst" that are added separately to the reaction mixture, but which are believed to assemble to a multi-subunit structure in the mixture.

**Comment by StephanM87** [comment]
Ok great. I agree, then I would close this issue and test this approach in the furture with a suitbale data set
