### ISSUE TITLE
Whole cell biocatalyst / Fermentation

### ISSUE THREAD

**Issue by KatrinRosenthal** [StephanM87/Strenda-biocatalysis#26]
Perhaps an awkward question and to make sure we have thought about it: We exclude fermentative processes, right? According to the definition, they do not belong to biocatalysis, but they might be interesting as the next extension ;-)

**Comment by StephanM87** [comment]
I also thought about this, and I think you are absolutely right. I think, the question, we have to answer will be when if and how to implement this in the upcoming catalogue, therefore, I have added this topic as a possible agenda point for the upcoming meeting #28
