### ISSUE TITLE
Storage conditions: add additives

### ISSUE THREAD

**Issue by KatrinRosenthal** [StephanM87/Strenda-biocatalysis#27]
- additives

- Type: string

- Description: Have you added an additive?

**Comment by StephanM87** [comment]
Hello @KatrinRosenthal,

thank you very much for the great input, I added the additives to the storage conditions. If you want to review it, you can check out the catalogue or have a look to the commit: https://github.com/StephanM87/Strenda-biocatalysis/commit/2f4e57616746b88d00ab62fb6fd9bec3ee52c052
