### ISSUE TITLE
Sampling issues - re-opened

### ISSUE THREAD

**Issue by PeterHalling** [StephanM87/Strenda-biocatalysis#29]
Sorry for the delay, but I have now examined the current structure and have some comments:

Default sampling
If the reaction mixture is a homogeneous solution, some of the attributes asked for are not needed, they should not affect the results - the sample volume, whether the mixture was mixed during sampling.
Opening of a closed vessel, and details of the gas phase in it, may be relevant where exchange of materials with the gas phase is important. But I think this is better handled as a case of Specialised Sampling – treat the reaction mixture now as multi-phase (gas and liquid). 
Sample time is clearly required, but would normally be part of the data, not metadata – i.e. there would be a table of sample times and analytical data on that sample
“Time at which the sample was taken” could be misunderstood. We actually want the time at which the reaction was stopped (we think). This might be the time at which the sample was mixed with a stop reagent, heated or frozen. If the sample is from a liquid phase from which an immobilised biocatalyst has temporarily settled out, it will be the time of removal. 

Sampling_procedure_from_heterogeneous_reaction_mixtures
Probably should ask for some simple details of how sampling of just the selected phase was achieved.
Consider also the possibility that people attempt to take a representative sample of the whole reaction mixture. But this is probably fairly uncommon, might leave as later enhancement.

Sample_preprocessing
I’m not sure this term will be clear to users. I think “Treatment to stop reaction” would be clear, and covers those processing steps that are specific to biocatalysis, where we can claim expert knowledge. Samples may then be further processed (e.g. extraction, derivatisation) before introducing to analytical equipment. But I think we are better to leave specification of metadata here to experts in the analytical techniques. I wouldn’t trust myself (and I’m sure others wouldn’t) to say what is critical in preparation of samples for GC, say.

**Comment by StephanM87** [comment]
This issue is a follow up from issue #24

**Comment by StephanM87** [comment]
>Default sampling
If the reaction mixture is a homogeneous solution, some of the attributes asked for are not needed, they should not affect the results - the sample volume, whether the mixture was mixed during sampling.
Opening of a closed vessel, and details of the gas phase in it, may be relevant where exchange of materials with the gas phase is important. But I think this is better handled as a case of Specialised Sampling – treat the reaction mixture now as multi-phase (gas and liquid).
Sample time is clearly required, but would normally be part of the data, not metadata – i.e. there would be a table of sample times and analytical data on that sample
“Time at which the sample was taken” could be misunderstood. We actually want the time at which the reaction was stopped (we think). This might be the time at which the sample was mixed with a stop reagent, heated or frozen. If the sample is from a liquid phase from which an immobilised biocatalyst has temporarily settled out, it will be the time of removal.

@PeterHalling  should we change default sampling to sampling from homogeneous reaction mixtures and remove the sampling __time, vesse, opened and mixed during sampling__?,

**Comment by PeterHalling** [comment]
Well, in the simple case (no gas exchange) of a homogeneous solution mixture, I think the only thing that needs specified is how the reaction was stopped - and that is always needed, simply removing a sample does nothing to stop the enzyme(s) in it continuing to work on the reactants in it. But perhaps the simplest way to structure the tree on sampling is to start with:
Reaction mixture is a homogeneous solution with dissolved enzyme(s)
Reaction mixture has more than one phase

**Comment by StephanM87** [comment]
I think I need to invest some more time in this issue, also to understand the aspects correctly. I would like to prepare a graph and discuss this with you. Would you thereby be interested in an online call in the upcoming week?

**Comment by PeterHalling** [comment]
Hi,

Yes, happy to chat - perhaps next week after I have made other comments. I should be available (all times CEST):
Mon 3/4: 9-11
Tue 4/4: 9-11
Wed 5/4: 9-11
Thu 6/4: 9-18

Peter

**Comment by StephanM87** [comment]
1. In sampling, the gas phase needs to be implemented
- Additional feature gas 
- Advanced attributes: Cases where exchange with the gas is important
- Only one category of homogeneous mixing

2. Heterogeneous reaction mixtures
- Split into: Sample taken from only one phase (not mixed) and taking a representative sample (mixed)
- How was the Phase separation realised
